ASPNETDemo3/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNETDemo3.Data;
using Microsoft.AspNetCore.Authorization;

namespace ASPNETDemo3.Controllers
{
    public class FoodsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public FoodsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Foods
        [Authorize]
        public async Task<IActionResult> Index()
        {
              return _context.Foods != null ? 
                          View(await _context.Foods.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Foods'  is null.");
        }

        // GET: Foods/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Foods == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description")] Food food)
        {
            if (ModelState.IsValid)
            {
                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return Json(ModelState);
            }
            return View(food);
        }

        // GET: Foods/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Foods == null)
            {
                return NotFound();
            }

            var food = await _context.Foods.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Description")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Foods == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Foods == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Foods'  is null.");
            }
            var food = await _context.Foods.FindAsync(id);
            if (food != null)
            {
                _context.Foods.Remove(food);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
          return (_context.Foods?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ASPNETDemo3/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNETDemo3.Data;
using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authorization;
using ASPNETDemo3.Models;
using System.Drawing.Printing;

namespace ASPNETDemo3.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var lobbies = _context.Lobbies.Where(l => l.status > 0).ToList();
            ViewBag.lobbies = lobbies;
            var filter = new OrderFilterModel
            {
                TotalCount = 0,
                PageSize = 6,
                Page = int.TryParse(Request.Query["page"], out int page_param) ? page_param : 1,
                search = Request.Query["search"],
                status = int.TryParse(Request.Query["status"], out int status_param) ? status_param : null,
                lobbyId = int.TryParse(Request.Query["lobbyId"], out int lobbyId_param) ? lobbyId_param : null,
                DateFrom = DateTime.TryParse(Request.Query["DateFrom"], out DateTime DateFrom_param) ? DateFrom_param : DateTime.MinValue,
                DateTo = DateTime.TryParse(Request.Query["DateTo"], out DateTime DateTo_param) ? DateTo_param : DateTime.MinValue
            };
            ViewBag.FilterModel = filter;

            IQueryable<Order> query = _context.Orders.Include(o => o.Lobby)
                .Where(order =>
                    (string.IsNullOrEmpty(filter.search) || EF.Functions.Like(order.customerName, $"%{filter.search}%")) &&
                    (filter.status == null || order.status == filter.status) &&
                    (filter.lobbyId == null || order.lobbyId == filter.lobbyId) &&
                    (filter.DateFrom == DateTime.MinValue || order.dateAt >= filter.DateFrom) &&
                    (filter.DateTo == DateTime.MinValue || order.dateAt <= filter.DateTo) &&
                    order.status > -1);

            int totalCount = query.Count();
            filter.TotalCount = totalCount;

            var applicationDbContext = query
                .Skip((filter.Page - 1) * filter.PageSize)
                .Take(filter.PageSize)
                .ToListAsync();

            return View(await applicationDbContext);
        }

        // GET: Orders/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Lobby)
                .Include(o => o.OrderTables)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            List<Lobby> lobbies = _context.Lobbies.ToList();
            ViewBag.Lobbies = lobbies;
            ViewBag.order = order;
            return View(order);
            //var json = JsonSerializer.Serialize(order, new JsonSerializerOptions
            //{
            //    ReferenceHandler = ReferenceHandler.Preserve,
            //    //PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            //    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            //    //IgnoreReadOnlyProperties = true,
            //    //WriteIndented = true
            //});
            //return Json(json);
        }

        // GET: Orders/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id");
            var lobbies = _context.Lobbies.ToList();
            ViewBag.lobbies = lobbies;
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,lobbyId,customerName,customerPhone,groomName,brideName,ca,dateAt,status,createdAt")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return Json(ModelState);
            }
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id", order.lobbyId);
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id", order.lobbyId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,lobbyId,customerName,customerPhone,groomName,brideName,ca,dateAt,status,createdAt")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.Alert = "Cập nhật thành công";
                return RedirectToAction("Details", new { id = order.Id });
            }
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id", order.lobbyId);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Lobby)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                order.status = -1;
                _context.Update(order);
                //_context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> Confirm(int? id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                order.status = 2;
                _context.Update(order);
                //_context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = order.Id });
        }

        public async Task<IActionResult> Cancel(int? id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                order.status = 0;
                _context.Update(order);
                //_context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new {id = order.Id });
        }

        public async Task<IActionResult> Payment(int? id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.Include(o => o.OrderTables).FirstOrDefaultAsync(o => o.Id == id);
            if (order != null)
            {
                order.status = 3;
                order.TotalPrice = order.OrderTables.Sum(t => t.TotalPrice);

ASPNETDemo3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETDemo3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPNETDemo3.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/x-icon">
    <title>Admin </title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap" rel="stylesheet">
    <!-- Font Awesome-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/font-awesome.css">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/icofont.css">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/themify.css">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/flag-icon.css">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/feather-icon.css">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/owlcarousel.css">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/bootstrap.css">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <link id="color" rel="stylesheet" href="~/assets/css/color-1.css" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/responsive.css">
    <!-- Data table-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/datatables.css">
    <!-- Select2 -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/vendors/select2.css"/>
    <script src="~/assets/js/jquery-3.5.1.min.js"></script>
</head>
<body>
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNETDemo3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPNETDemo3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <div class="page-wrapper compact-wrapper" id="pageWrapper">
        <div class="page-main-header">
            <div class="main-header-right row m-0">
                <div class="main-header-left">
                    <div class="logo-wrapper"><a href="index.html"><img class="img-fluid" src="../assets/images/logo/logo.png" alt=""></a></div>
                </div>
                <div class="toggle-sidebar"><i class="status_toggle middle" data-feather="align-center" id="sidebar-toggle"></i></div>
                <div class="nav-right col pull-right right-menu">
                    <partial name="_LoginPartial" />
                </div>
                <div class="d-lg-none col mobile-toggle pull-right"><i data-feather="more-horizontal"></i></div>
            </div>
        </div>
        <div class="page-body-wrapper sidebar-icon">
            <header class="main-nav">
                <div class="logo-wrapper"><a href="index.html"><img class="img-fluid" src="../assets/images/logo/logo.png" alt=""></a></div>
                <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="../assets/images/logo/logo-icon.png" alt=""></a></div>
                <div class="morden-logo"><a href="index.html"><img class="img-fluid" src="../assets/images/logo/morden-logo.png" alt=""></a></div>
                <nav>
                    <div class="main-navbar">
                        <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
                        <div id="mainnav">
                            <ul class="nav-menu custom-scrollbar">
                                <li class="back-btn">
                                    <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                                </li>                           
                                <li class="dropdown">
                                    <a class="nav-link menu-title link-nav" asp-controller="Foods" asp-action="Index"><i data-feather="coffee"></i><span>Món Ăn</span></a>
                                </li>
                                <li class="dropdown">
                                    <a class="nav-link menu-title link-nav" asp-controller="Lobbies" asp-action="Index"><i data-feather="airplay"></i><span>Sảnh</span></a>
                                </li>
                                <li class="dropdown">
                                    <a class="nav-link menu-title link-nav" asp-controller="Orders" asp-action="Index"><i data-feather="file-plus"></i><span>Đặt tiệc</span></a>
                                </li>
                                <hr/>
                            </ul>
                        </div>
                        <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
                    </div>
                </nav>
            </header>
            <div class="page-body">
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- Container-fluid starts-->
                <div class="container-fluid blog-page">
                </div>
                <!-- Container-fluid Ends-->
            </div>
            <!-- tap on top starts-->
            <div class="tap-top"><i class="icon-control-eject"></i></div>
            <!-- tap on tap ends-->
            <!-- footer start-->
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- latest jquery-->
    <script src="~/assets/js/jquery-3.5.1.min.js"></script>
    <!-- feather icon js-->
    <script src="~/assets/js/icons/feather-icon/feather.min.js"></script>
    <script src="~/assets/js/icons/feather-icon/feather-icon.js"></script>
    <!-- Sidebar jquery-->
    <script src="~/assets/js/sidebar-menu.js"></script>
    <script src="~/assets/js/config.js">   </script>
    <!-- Bootstrap js-->
    <script src="~/assets/js/bootstrap/popper.min.js"></script>
    <script src="~/assets/js/bootstrap/bootstrap.min.js"></script>
    <!-- Plugins JS start-->
    <script src="~/assets/js/owlcarousel/owl.carousel.js"></script>
    <script src="~/assets/js/owlcarousel/owl-custom.js"></script>
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <!-- <script src="~/assets/js/theme-customizer/customizer.js"></script> -->
    <script src="~/assets/js/script.js"></script>
    <!-- login js-->
    <!-- Plugin used-->
    <script src="~/assets/js/datatable/datatables/jquery.dataTables.min.js"></script>
    <script src="~/assets/js/select2/select2.full.min.js"></script>
    <!-- tap on top starts-->
    <div class="tap-top"><i class="icon-control-eject"></i></div>
    <!-- tap on tap ends-->
    <script>
        $(document).ready(function(){
            $('#user-table').DataTable();
            $('#FoodIds').select2();

        })
    </script>
    @if (ViewBag.AlertMessage != null)
    {
        <script>
            $(document).ready(function () {
                alert('@ViewBag.Alert');
            })
        </script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>