ASPNETDemo3/Controllers/OrderTablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNETDemo3.Data;
using ASPNETDemo3.Models;
using NuGet.Packaging;

namespace ASPNETDemo3.Controllers
{
    public class OrderTablesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderTablesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderTables
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.OrderTables.Include(o => o.Order);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: OrderTables/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.OrderTables == null)
            {
                return NotFound();
            }

            var orderTable = await _context.OrderTables
                .Include(o => o.Order)
                .Include(o => o.Foods)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderTable == null)
            {
                return NotFound();
            }
            ViewBag.OrderTable = orderTable;
            return View(orderTable);
        }

        // GET: OrderTables/Create
        public async Task<IActionResult> Create()
        {
            ViewData["OrderId"] = Request.Query["OrderId"];
            List<Food> foods = _context.Foods.ToList();
            var order = await _context.Orders.FirstOrDefaultAsync(o => o.Id == int.Parse(Request.Query["OrderId"]));
            
            ViewBag.Foods = foods;
            ViewBag.order = order;
            var model = new DataOrderTable
            {
                OrderTable = new OrderTable()
            };
            return View(model);
        }

        // POST: OrderTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DataOrderTable dataOrderTable)
        {

            if (ModelState.IsValid)
            {
                var OrderTable = dataOrderTable.OrderTable;
                var FoodIds = dataOrderTable.FoodIds.ToList();
                var Foods = _context.Foods.Where(f => FoodIds.Contains(f.Id)).ToList();

                var UnitPrice = 0;
                var TotalPrice = 0;
                UnitPrice = Foods.Sum(food => food.Price);
                TotalPrice = (int)(UnitPrice * OrderTable.Amount);

                OrderTable.UnitPrice = UnitPrice;
                OrderTable.TotalPrice = TotalPrice;

                if (OrderTable != null && Foods.Any())
                {
                    _context.Add(OrderTable);

                    foreach (var food in Foods)
                    {
                        // Ensure that the Food entities are tracked or explicitly set their state
                        // _context.Entry(food).State = EntityState.Added;
                        OrderTable.Foods.Add(food);
                    }

                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "Orders", new { id = OrderTable.OrderId});
                }

                //_context.Add(OrderTable);
                //await _context.SaveChangesAsync();

                //if (Foods.Any())
                //{
                //    OrderTable.Foods.AddRange(Foods);
                //    await _context.SaveChangesAsync();
                //}    
                
                //return RedirectToAction(nameof(Index));

            }
            else
            {
                return Json(ModelState);
            }
            ViewData["OrderId"] = Request.Query["OrderId"];
            List<Food> foods = _context.Foods.ToList();
            ViewBag.Foods = foods;
            return View(dataOrderTable);
        }

        // GET: OrderTables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.OrderTables == null)
            {
                return NotFound();
            }

            var orderTable = await _context.OrderTables.FindAsync(id);
            if (orderTable == null)
            {
                return NotFound();
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Id", orderTable.OrderId);
            return View(orderTable);
        }

        // POST: OrderTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderId,table_name,UnitPrice,Amount,TotalPrice,status,createdAt")] OrderTable orderTable)
        {
            if (id != orderTable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderTableExists(orderTable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Id", orderTable.OrderId);
            return View(orderTable);
        }

        // GET: OrderTables/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.OrderTables == null)
            {
                return NotFound();
            }

            var orderTable = await _context.OrderTables
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderTable == null)
            {
                return NotFound();
            }

            return View(orderTable);
        }

        // POST: OrderTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.OrderTables == null)
            {
                return Problem("Entity set 'ApplicationDbContext.OrderTables'  is null.");
            }
            var orderTable = await _context.OrderTables.FindAsync(id);
            if (orderTable != null)
            {
                _context.OrderTables.Remove(orderTable);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderTableExists(int id)
        {
          return (_context.OrderTables?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ASPNETDemo3/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNETDemo3.Data;
using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authorization;
using ASPNETDemo3.Models;
using System.Drawing.Printing;

namespace ASPNETDemo3.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var lobbies = _context.Lobbies.Where(l => l.status > 0).ToList();
            ViewBag.lobbies = lobbies;
            var filter = new OrderFilterModel
            {
                TotalCount = 0,
                PageSize = 6,
                Page = int.TryParse(Request.Query["page"], out int page_param) ? page_param : 1,
                search = Request.Query["search"],
                status = int.TryParse(Request.Query["status"], out int status_param) ? status_param : null,
                lobbyId = int.TryParse(Request.Query["lobbyId"], out int lobbyId_param) ? lobbyId_param : null,
                DateFrom = DateTime.TryParse(Request.Query["DateFrom"], out DateTime DateFrom_param) ? DateFrom_param : DateTime.MinValue,
                DateTo = DateTime.TryParse(Request.Query["DateTo"], out DateTime DateTo_param) ? DateTo_param : DateTime.MinValue
            };
            ViewBag.FilterModel = filter;

            IQueryable<Order> query = _context.Orders.Include(o => o.Lobby)
                .Where(order =>
                    (string.IsNullOrEmpty(filter.search) || EF.Functions.Like(order.customerName, $"%{filter.search}%")) &&
                    (filter.status == null || order.status == filter.status) &&
                    (filter.lobbyId == null || order.lobbyId == filter.lobbyId) &&
                    (filter.DateFrom == DateTime.MinValue || order.dateAt >= filter.DateFrom) &&
                    (filter.DateTo == DateTime.MinValue || order.dateAt <= filter.DateTo) &&
                    order.status > -1);

            int totalCount = query.Count();
            filter.TotalCount = totalCount;

            var applicationDbContext = query
                .Skip((filter.Page - 1) * filter.PageSize)
                .Take(filter.PageSize)
                .ToListAsync();

            return View(await applicationDbContext);
        }

        // GET: Orders/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Lobby)
                .Include(o => o.OrderTables)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            List<Lobby> lobbies = _context.Lobbies.ToList();
            ViewBag.Lobbies = lobbies;
            ViewBag.order = order;
            return View(order);
            //var json = JsonSerializer.Serialize(order, new JsonSerializerOptions
            //{
            //    ReferenceHandler = ReferenceHandler.Preserve,
            //    //PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            //    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            //    //IgnoreReadOnlyProperties = true,
            //    //WriteIndented = true
            //});
            //return Json(json);
        }

        // GET: Orders/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id");
            var lobbies = _context.Lobbies.ToList();
            ViewBag.lobbies = lobbies;
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,lobbyId,customerName,customerPhone,groomName,brideName,ca,dateAt,status,createdAt")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return Json(ModelState);
            }
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id", order.lobbyId);
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id", order.lobbyId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,lobbyId,customerName,customerPhone,groomName,brideName,ca,dateAt,status,createdAt")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.Alert = "Cập nhật thành công";
                return RedirectToAction("Details", new { id = order.Id });
            }
            ViewData["lobbyId"] = new SelectList(_context.Lobbies, "Id", "Id", order.lobbyId);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Lobby)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                order.status = -1;
                _context.Update(order);
                //_context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> Confirm(int? id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                order.status = 2;
                _context.Update(order);
                //_context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = order.Id });
        }

        public async Task<IActionResult> Cancel(int? id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                order.status = 0;
                _context.Update(order);
                //_context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new {id = order.Id });
        }

        public async Task<IActionResult> Payment(int? id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.Include(o => o.OrderTables).FirstOrDefaultAsync(o => o.Id == id);
            if (order != null)
            {
                order.status = 3;
                order.TotalPrice = order.OrderTables.Sum(t => t.TotalPrice);

ASPNETDemo3/Views/Orders/AddOrderTables.cshtml
@model ASPNETDemo3.Data.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var foods = ViewBag.Foods;
}

<h4>Thông tin đặt tiệc</h4>
<p>@Model.customerName</p>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <h4>Thêm mới thực đơn</h4>
            </div>
            <div class="col-6 text-end">
                <a class="btn btn-info" asp-controller="" asp-action="Index">Thêm</a>
            </div>  
        </div>
        <form asp-controller="Orders" asp-action="AddOrderTables">
            @* <input asp-for="OrderId" hidden value=@Model.Id/>
            <div class="form-group">
                <label asp-for="table_name" class="control-label"></label>
                <input asp-for="table_name" class="form-control" />
                <span asp-validation-for="table_name" class="text-danger"></span>
            </div> *@
        </form>
    </div>
</div>

ASPNETDemo3/Views/Orders/Create.cshtml
@model ASPNETDemo3.Data.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Tạo mới phiếu đặt tiệc</h4>
<hr />
<div class="container">
    <form asp-action="Create">
    <div class="row">
        <div class="col-md-6">
           
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <h5>Thông tin người đặt</h5>
                <div class="form-group">
                    <label asp-for="customerName" class="control-label">Khách đặt tiệc</label>
                    <input asp-for="customerName" class="form-control" required/>
                    <span asp-validation-for="customerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customerPhone" class="control-label">Số điện thoại khách đặt</label>
                    <input asp-for="customerPhone" class="form-control" />
                    <span asp-validation-for="customerPhone" class="text-danger"></span>
                </div>

        </div>
        <div class="col-md-6">
            <h5>Thông tin tiệc cưới</h5>
            <div class="form-group">
                <label asp-for="groomName" class="control-label">Tên chú rể</label>
                <input asp-for="groomName" class="form-control" />
                <span asp-validation-for="groomName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brideName" class="control-label">Tên cô dâu</label>
                <input asp-for="brideName" class="form-control" />
                <span asp-validation-for="brideName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ca" class="control-label">Ca</label>
                <select asp-for="ca" class="form-control" required>
                    <option value="Ca sáng (8:00 - 12:00)"> Ca sáng (8:00 - 12:00)</option>
                    <option value="Ca chiều (13:00 - 17:00)"> Ca chiều (13:00 - 17:00)</option>
                    <option value="Ca tối (18:00 - 22:00)"> Ca tối (18:00 - 22:00)</option>
                </select>
                <span asp-validation-for="ca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateAt" class="control-label">Ngày tổ chức</label>
                <input asp-for="dateAt" class="form-control" required type="date"/>
                <span asp-validation-for="dateAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lobbyId" class="control-label">Sảnh</label>
                <select asp-for="lobbyId" class="form-control">
                        @foreach(var lobby in ViewBag.lobbies)
                        {
                            <option value="@lobby.Id">@lobby.Name (tối thiểu @lobby.MinCountTable bàn)</option>            
                        }
                </select>
            </div>
            </div>
        <div class="col-12">
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
    </form>
</div>

    
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPNETDemo3/Views/Orders/Details.cshtml
@model ASPNETDemo3.Data.Order
@using System.Text.Json;
@using System.Text.Json.Serialization;
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var lobbies = ViewBag.Lobbies;
    var order = ViewBag.order;
}

<div class="row">
    <div class="col-6">
        <h4>Thông tin đặt tiệc</h4>
    </div>
    <div class="col-6 d-flex justify-content-end">
        @if (order.status == 1)
        {
            @Html.Raw("<button class='btn btn-danger' style='margin-right: 8px;' id='cancel_btn'>Hủy</button><button class='btn btn-primary' id='confirm_btn'>Xác nhận Đặt</button>");
        }
        @if (order.status == 2)
        {
            @Html.Raw("<button class='btn btn-danger' style='margin-right: 8px;' id='cancel_btn'>Hủy</button><button class='btn btn-success' id='payment_btn'>Thanh toán</button>")
            ;
        }
    </div>
</div>
<div class="card mt-2">
    <div class="card-body">
        <p>
            Trạng thái:
            <span>
                @if (order.status == 0)
                {
                    @Html.Raw("<span class='bagde bg-danger rounded text-center p-1'>Hủy</span>")
                    ;
                }
                @if (order.status == 1)
                {
                    @Html.Raw("<span class='bagde bg-warning rounded text-center p-1'>Đang đặt</span>");
                }
                @if (order.status == 2)
                {
                    @Html.Raw("<span class='bagde bg-primary rounded text-center p-1'>Đã xác nhận</span>")
                    ;
                }
                @if (order.status == 3)
                {
                    @Html.Raw("<span class='bagde bg-success rounded text-center p-1'>Thanh toán</span>")
                    ;
                }
            </span>
        </p>
        @if (order.status == 3)
        {
            @Html.Raw($"<p>Ngày thanh toán: {order.PaymentAt}</p>")
            ;
        }
    </div>
</div>
<div class="card mt-2">
    <div class="card-body">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="status" value="@order.status" />
            <div class="row">
                <div class="col-6">
                    <h5>Thông tin người đặt</h5>
                    <div class="form-group">
                        <label asp-for="customerName" class="control-label">Khách đặt tiệc</label>
                        <input asp-for="customerName" class="form-control" required />
                        <span asp-validation-for="customerName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="customerPhone" class="control-label">Số điện thoại khách đặt</label>
                        <input asp-for="customerPhone" class="form-control" />
                        <span asp-validation-for="customerPhone" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="lobbyId" class="control-label">Sảnh</label>
                        <select asp-for="lobbyId" class ="form-control">                     
                            @foreach (var lobby in lobbies)
                            {
                                <option value="@lobby.Id">@lobby.Name - (lượng bàn tối thiểu: @lobby.MinCountTable)</option>
                            }
                        </select>
                        <span id="lobby_min" style="display:none"></span>
                    </div> 
                </div>
                <div class="col-6">
                    <h5>Thông tin tiệc cưới</h5>
                    <div class="form-group">
                        <label asp-for="groomName" class="control-label">Tên chú rể</label>
                        <input asp-for="groomName" class="form-control" />
                        <span asp-validation-for="groomName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="brideName" class="control-label">Tên cô dâu</label>
                        <input asp-for="brideName" class="form-control" />
                        <span asp-validation-for="brideName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ca" class="control-label">Ca</label>
                        <select asp-for="ca" class="form-control">
                            <option value="Ca sáng (8:00 - 12:00)"> Ca sáng (8:00 - 12:00)</option>
                            <option value="Ca chiều (13:00 - 17:00)"> Ca chiều (13:00 - 17:00)</option>
                            <option value="Ca tối (18:00 - 22:00)"> Ca tối (18:00 - 22:00)</option>
                        </select>
                        <span asp-validation-for="ca" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="dateAt" class="control-label">Ngày tổ chức</label>
                        <input asp-for="dateAt" class="form-control" required type="date"/>
                        <span asp-validation-for="dateAt" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Cập nhật" class="btn btn-primary" id="btn_update"/>
                    </div>
                </div>
            </div>
                    
        </form>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <h4>Thông tin bàn ăn</h4>
                <h5>Tổng số bàn: <span id="count_table">0</span></h5>
                <h5>Tổng tiền: <span id="total_price">0</span>đ</h5>
            </div>
            <div class="col-6 text-end">
                <a class="btn btn-info" asp-controller="OrderTables" asp-action="Create" asp-route-orderId="@order.Id" id="btn_add_table">Thêm</a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Tên bàn</th>
                        <th>Số lượng</th>
                        <th>Đơn giá</th>
                        <th>Thành tiền</th>
                        <th>Lựa chọn</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var orderTable in @order.OrderTables)
                    {
                        
                        <tr>
                            <td>@orderTable.table_name</td>
                            <td>@orderTable.Amount</td>
                            <td>@orderTable.UnitPrice.ToString("#,##0")</td>
                            <td>@orderTable.TotalPrice.ToString("#,##0")</td>
                            <td>
                                <a class="btn btn-primary" asp-controller="OrderTables" asp-action="Details" asp-route-id="@orderTable.Id" asp-route-orderId="@order.Id">Chi tiết</a>
                                <a class="btn btn-danger btn_delete_table" asp-controller="OrderTables" asp-action="Delete" asp-route-id="@orderTable.Id">Xóa</a>
                            </td>
                        </tr>
                    }
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    @if (order.status == 0 || order.status == 3)
    {
        @Html.Raw("$(document).ready(()=>{$('#btn_update')[0].style.display='none';$('#btn_add_table')[0].style.display='none';const del_table_btns=$('.btn_delete_table');for(i=0;i<del_table_btns.length;i++){del_table_btns[i].style.display='none';}})");
    }

    @if (order.status == 2)
    {
        @Html.Raw("$(document).ready(()=>{$('#btn_update')[0].style.display='none';})");
    }


    $(document).ready(() => {
        $("#cancel_btn").on('click', (e) => {
            let ok = confirm('Xác nhận hủy đơn đặt ?');
            if (ok) {
                window.location.assign(`/Orders/Cancel/${@order.Id}`);
            }
        })
    })

    $(document).ready(() => {
        $("#confirm_btn").on('click', (e) => {
            let ok = confirm('Xác nhận đặt ?');
            if (ok) {
                const min_count_table = parseInt($('#lobby_min')[0].innerHTML);
                const current_count_table = parseInt($('#count_table')[0].innerHTML);
                if (current_count_table >= min_count_table) {
                    window.location.assign(`/Orders/Confirm/${@order.Id}`);
                } else {
                    alert(`Số bàn đặt chưa đủ ${current_count_table}/${min_count_table}`);
                }
               
            }
        })
    })

    $(document).ready(() => {
        $("#payment_btn").on('click', (e) => {
            let ok = confirm('Xác nhận thanh toán ?');
            if (ok) {
                window.location.assign(`/Orders/Payment/${@order.Id}`);
            }
        })
    })

    $(document).ready(() => {
        let total_price = 0;
        @foreach (var ot in @order.OrderTables)
        {
            var totalPrice = ot.TotalPrice;
        @Html.Raw($"total_price += {totalPrice};")
        ;
        }
        $('#total_price')[0].innerHTML = total_price.toLocaleString('en-US', { style: 'decimal' });

        let count_table = 0;
        @foreach (var ot in @order.OrderTables)
        {
            var count_table = ot.Amount;
            @Html.Raw($"count_table += {count_table};")
            ;
        }
        $('#count_table')[0].innerHTML = count_table.toLocaleString('en-US', { style: 'decimal' });

        $("#lobby_min")[0].innerHTML = @order.Lobby.MinCountTable;
    })
</script>